### ISSUE TITLE
[code review] csi improvements

### ISSUE THREAD

**Issue by msau42** [deislabs/secrets-store-csi-driver#100]
Assuming driver is only supported in 1.15+

Comments on helm chart:
* Remove crd-csi-driver-registry.yaml. This is the alpha CRD that was used in 1.13, but since 1.14, K8s is using the in-tree v1beta object: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#csidriver-v1beta1-storage-k8s-io
* Set `CSIDriver.AttachedRequired = false` in https://github.com/deislabs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/csidriver.yaml.  This will allow you to delete csi-secrets-store-attacher.yaml entirely
* csi-attacher service account and roles/rolebindings can be removed once attacher is removed
* node-driver-registrar shouldn't require any rbacs anymore because it doesn't call k8s apis. So you can probably rename your service account to your driver name or something for the secretsClass rbacs. Also check with sig-auth on these rbacs. In general I recommend the names of objects, especially for non-namespaced objects like ClusterRoleBindings, to be specific, to not cause naming conflicts with other csi drivers.

Comments on csi node implementation:
* In NodePublishVolume, are providers required to mount the volume, or do they just populate the directory with data? 
* Bind mounting "/tmp" to the targetPath seems odd: https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store/nodeserver.go#L164.  What happens if the driver container restarts? I'm guessing since bind mounting is on the inode, the existing container will continue to work, and Unpublish should also work too.
* Double check idempotency of NodePublish/Unpublish. For example, if NodePublish gets called twice, and it's already correctly mounted, we should return success. Looking at the current code, it seems like we'll bind mount it twice? Which can potentially cause mounts to leak on cleanup.  Similarly, Unpublish should return success if it's already unpublished.
* Usage of IsLikelyNotMountPoint() also doesn't work if the bind mount is from the same fs as the kubelet's rootfs (if you look at the implementation, it just checks if the parent directory is in the same fs or not). 
* results from https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store/nodeserver.go#L220 are unused?
* Make sure providers don't include any sensitive info in the error msg: https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store/nodeserver.go#L213
* Do you only support read-only? If so, `NodePublishVolumeRequest.ReadOnly` should be validated. 

General architecture questions:
* Can contents of the secrets change dynamically? Would you want the volume to be updated with the latest content, similar to how the current Secrets volume works?

I didn't review the CreateVolume/PV implementations since that's the legacy model. I also didn't review any of the providers

**Comment by ritazh** [comment]
Thanks for the review @msau42! 

> In NodePublishVolume, are providers required to mount the volume, or do they just populate the directory with data?

providers only writes to the directory with data

> Make sure providers don't include any sensitive info in the error msg:

yes, there's no sensitive information in the err msg

> Can contents of the secrets change dynamically? Would you want the volume to be updated with the latest content, similar to how the current Secrets volume works?

Not today. The content is only updated when the pod is recreated. Dynamic update of secrets is in the backlog to be implemented in the future.

**Comment by ritazh** [comment]
@msau42 Are you aware of any csi driver naming conventions? This driver is currently named: `secrets-store.csi.k8s.com`.  The hostpath one is: `hostpath.csi.k8s.io`.

**Comment by msau42** [comment]
Once it gets moved to a kubernetes-sigs repo, then we can use the "k8s.io" domain

**Comment by ritazh** [comment]
Closing as all issues have been addressed
