### ISSUE TITLE
[code review] idempotency of NodePublish/Unpublish

### ISSUE THREAD

**Issue by ritazh** [deislabs/secrets-store-csi-driver#106]
* Double check idempotency of NodePublish/Unpublish. For example, if NodePublish gets called twice, and it's already correctly mounted, we should return success. Looking at the current code, it seems like we'll bind mount it twice? Which can potentially cause mounts to leak on cleanup.  Similarly, Unpublish should return success if it's already unpublished.
* Usage of IsLikelyNotMountPoint() also doesn't work if the bind mount is from the same fs as the kubelet's rootfs (if you look at the implementation, it just checks if the parent directory is in the same fs or not). 
* results from https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store/nodeserver.go#L220 are unused?

part of #100

**Comment by aramase** [comment]
Closed with https://github.com/deislabs/secrets-store-csi-driver/pull/124
