### ISSUE TITLE
Deployment - Unable to mount volumes for csi secrets store driver pods

### ISSUE THREAD

**Issue by phillipgibson** [deislabs/secrets-store-csi-driver#22]
Just build a new AKS cluster (1.12.5) and when initially deploying the helm chart none of the secret store pods in the dev namespace are able to run do to a volume not being mounted. 

Warning  FailedMount  1m                kubelet, aks-nodepool1-26873499-2  Unable to mount volumes for pod "csi-secrets-store-secrets-store-csi-driver-bg2wf_dev(385cb061-3a0f-11e9-8715-4e92e05d98d9)": timeout expired waiting for volumes to attach or mount for pod "dev"/"csi-secrets-store-secrets-store-csi-driver-bg2wf". list of unmounted volumes=[registration-dir]. list of unattached volumes=[socket-dir mountpoint-dir registration-dirazure-cred msi csi-driver-registrar-token-vfmtq]

**Comment by ritazh** [comment]
@phillipgibson We are leveraging the v1.0.0 CSI spec, which requires Kubernetes v1.13.0+.
