### ISSUE TITLE
Vault provider instructions

### ISSUE THREAD

**Issue by sozercan** [deislabs/secrets-store-csi-driver#75]
- deployment yamls and instructions for v1.13 and v1.15 seems to be almost identical from what i can tell
https://github.com/deislabs/secrets-store-csi-driver/tree/master/pkg/providers/vault#install-the-secrets-store-csi-driver-kubernetes-version-113x
https://github.com/deislabs/secrets-store-csi-driver/tree/master/pkg/providers/vault#install-the-secrets-store-csi-driver-kubernetes-version-115x
Should this just split up PV (for v1.13+) vs inline volume (for v1.15+)?

- does vault provider work with Helm installation? seems a bit confusing to have instructions on main readme use Helm and then vault has yamls for deployment

- on the vault setup, vault role creation seems to need the namespace which is used after the k8s components are created. since this is preliminary setup, this seems to be out of order slightly.
https://github.com/deislabs/secrets-store-csi-driver/blob/master/pkg/providers/vault/docs/vault-setup.md#vault-provider-for-secret-store-csi-driver

**Comment by ritazh** [comment]
Working on a PR for this
