### ISSUE TITLE
[code review] move init to handle

### ISSUE THREAD

**Issue by ritazh** [deislabs/secrets-store-csi-driver#95]
move [init](https://github.com/deislabs/secrets-store-csi-driver/blob/51d64fcf33d62b84143f666ed8bc387011652de5/pkg/secrets-store-csi-driver/main.go#L28-L33) into [handle](https://github.com/deislabs/secrets-store-csi-driver/blob/3047a16f3cd02466a4e8151d845cbf623dd4e2b3/pkg/secrets-store-csi-driver/main.go#L52-L55). Does os.Exit(0) at the end of the main do anything? It looks like it should be removed.

part of #92

**Comment by ritazh** [comment]
cc @malnick

**Comment by aramase** [comment]
Since we moved from `glog` to `logrus`, the `init` function has been removed - https://github.com/deislabs/secrets-store-csi-driver/pull/114/files#diff-00cf70fc0263609f2aca7b53967c2e0aL28-L34. So this issue is no longer required. 

cc @malnick @ritazh

**Comment by ritazh** [comment]
Closed via https://github.com/deislabs/secrets-store-csi-driver/pull/114
